New upstream version 2.3.25

diff --git a/scripts/make.in b/scripts/make.in
--- a/scripts/make.in
+++ b/scripts/make.in
@@ -1,6 +1,6 @@
 #!/bin/sh
-# $Id: make.in 6557 2011-12-14 11:33:04Z cher $
-# Copyright (c) 2011 Alexander Chernov <cher@ejudge.ru>
+# $Id: make.in 7188 2012-11-21 07:43:51Z cher $
+# Copyright (c) 2012 Alexander Chernov <cher@ejudge.ru>
 
 # Environment variables:
 #  EJ_MAKE_COMMAND
@@ -81,6 +81,20 @@ fi
 if ! cd "${EJ_PROGRAM_DIR}"
 then
     echo "Failed to change the current directory to ${EJ_PROGRAM_DIR}" 1>&2
+    exit 1
+fi
+
+# touch all files to quell "Modification time in future" warning
+touch *
+
+# remove the expected executable file (just in case)
+rm -f "${EJ_PROGRAM_NAME}"
+
+# remove all working file
+${EJ_MAKE_COMMAND} clean
+if [ $? != 0 ]
+then
+    echo "Makefile does not have 'clean' rule or it failed" 1>&2
     exit 1
 fi
 
